module.exports = {
  chatzotNight: "חצות הלילה",
  alotHaShachar: "עלות השחר",
  misheyakir: "זמן טלית ותפילין",
  misheyakirMachmir: "זמן טלית ותפילין (מחמיר)",
  sunset: "שקיעה",
  // dawn: "שחר",
  sunrise: "זריחה",
  sofZmanShma: 'סוף זמן קריאת שמע (גר"א)',
  sofZmanTfilla: 'סוף זמן תפילה (גר"א)',
  chatzot: "חצות היום",
  minchaGedola: "מנחה גדולה",
  minchaKetana: "מנחה קטנה",
  plagHaMincha: "פלג המנחה",
  tzeit42min: 'צאת הכוכבים (חזו"א)',
  sunset: "שקיעה",
  dusk: "צאת הכוכבים",
  tzeit85deg: "צאת הכוכבים 80°",
  tzeit42min: "צאת הכוכבים (42 דקות)",
  tzeit50min: "צאת הכוכבים (50 דקות)",
  tzeit72min: "צאת הכוכבים (רבינו תם)"
};
