module.exports = {
  chatzotNight: "חצות הלילה",
  alotHaShachar: "עלות השחר",
  misheyakir: "משיכיר",
  misheyakirMachmir: "משיכיר (מחמיר)",
  dawn: "שקיעה",
  sunrise: "זריחה",
  sofZmanShma: "סוף זמן קריאת שמע",
  sofZmanTfilla: "סוף זמן תפילה",
  chatzot: "חצות",
  minchaGedola: "מנחה גדולה",
  minchaKetana: "מנחה קטנה",
  plagHaMincha: "פלג המנחה",
  sunset: "שקיעה",
};
